### ISSUE TITLE
Zadanie 4 (Map)

### ISSUE THREAD

**Issue by arafalski** [anraf1001/object-oriented-programming#4]
Napisz klasę Map, która będzie posiadała `std::vector<Island> `przechowujący wszystkie wyspy na mapie, oraz zmienną `Island* currentPosition_` określającą aktualną pozycję gracza na mapie.

**Comment by piezol** [comment]
Mateusz changed the description of task (vector of Islands instead of vector of references to islands).
I've updated description accordingly.
